### PR TITLE
Fix biolink

### LINKED ISSUE #228: add REACTO prefix to biolink-model

### PR DESCRIPTION
**Pull request by jdr0887**
Adds reacto prefix (fixes #228) and fix parsing of https://biolink.github.io/biolink-model/context.jsonld since it changed format.

### CODE REVIEW

File: src/main/scala/org/renci/cam/Biolink.scala [hunk 1]
```diff
@@ -25,9 +25,9 @@ object Biolink {
     for {
       (biolinkPrefixes, classes, predicates) <- getBiolinkPrefixesAndClassesAndPredicatesFromFile
       local <- localPrefixes
-//      prefixes <- getBiolinkPrefixesFromFile
-      prefixes <- getBiolinkPrefixesFromURL.orElse(getBiolinkPrefixesFromFile)
-      combined = local ++ biolinkPrefixes ++ prefixes
+      prefixesFromFile <- getBiolinkPrefixesFromFile
+      prefixesFromURL <- getBiolinkPrefixesFromURL
+      combined = local ++ biolinkPrefixes ++ prefixesFromFile ++ prefixesFromURL
```
Comment (balhoff) [inline src/main/scala/org/renci/cam/Biolink.scala:30]: I think we've kind of lost the purpose of all these variants. The local file (currently "legacy_prefixes.json", could be renamed) is prefixes for namespaces we use but aren't in Biolink. The data in "prefixes.json" is just meant to be a fallback recent Biolink context in case the Biolink file isn't reachable for some reason. And I'm not sure exactly why we are taking the prefixes out of the Biolink model (biolinkPrefixes). I would expect these all to be in the Biolink context.

**Review by balhoff — CHANGES_REQUESTED** [review]

File: src/main/scala/org/renci/cam/Biolink.scala (hunk 1 above)
Comment (jdr0887) [reply src/main/scala/org/renci/cam/Biolink.scala:30]: Not sure I totally agree with this sentiment.  Yes, "prefixes.json" is a fallback for when https://biolink.github.io/biolink-model/context.jsonld can't be reached or if formatting changes were made (which happened a day or so ago).  Yes, "legacy_prefixes.json" is for prefixes not found in https://biolink.github.io/biolink-model/context.jsonld.  Yet, the prefixes from the https://biolink.github.io/biolink-model/biolink-model.yaml once included some mappings that were not found elsewhere.  Granted, the https://biolink.github.io/biolink-model/context.jsonld file seems to be changing readily & it might be that parsing https://biolink.github.io/biolink-model/biolink-model.yaml for prefixes is no longer necessary, however, it's an easy grab since we already parse it for classes & predicates.

**Review by balhoff — APPROVED** [review]
